######################################################################
# Automatically generated by qmake (2.01a) Tue Mar 11 22:57:42 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
