######################################################################
# Automatically generated by qmake (2.01a) Tue Mar 18 00:29:38 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
