######################################################################
# Automatically generated by qmake (2.01a) Sun Feb 17 22:45:35 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
